### ISSUE TITLE
default number of words to 15?

### ISSUE THREAD

**Issue by dooglus** [dcpos/bip39#11]
`src/index.html`:

    <input type="number" class="strength form-control" id="strength" value="12">

Each 3 words gives us 32 bits of entropy (and 1 bit of checksum). We need 160 bits of entropy for optimal security, since addresses are 160 bits long. That means we need 5 sets of 3 words, or 15 words. The default of 12 words only gives us 128 bits, which is pretty good but we can do better.

**Comment by iancoleman** [comment]
I used 12 as the default because most of the bip39 [test vectors](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#test-vectors) use 12.

https://github.com/trezor/python-mnemonic/blob/master/vectors.json

Also all the wallets I've looked at have been using 12 words.

But the logic behind 15 sounds quite reasonable. I'll make that change, or you're welcome to submit a pull request.

**Comment by hatgit** [comment]
For the sake of a healthy discussion on the topic, I would argue that we don't get 32 bits of entropy for every 3 words (although that might be true in one definition context), I tend to instead view that we get a minimum of 11 bits of entropy for every word except the last, and only partial bits of the last word (i.e. 7 bits for a 12 word mnemonic, where the checksum itself doesn't really expand the total entropy as it is deterministically calculated from the hash of the preceding 128 bits. In other words, while the 12 words are 132 bits (when included the checksum) and only provide 128 bits of security, the first 11 words get 11.6363636364 bits, but since they only need 11 each, the extra 0.6363636364 bits per word accumulate towards the last group and add up to 7 remaining bits (0.6363636364 x 11 = 7 bits), so the first 11 words gives us 121 bits of entropy, while the last word only provides 7 (again, I agree that  when dividing the 128 initial entropy by 12  we get 32 (and entropy must encode 32 bits at a time as per the BIP 39 spec) so it looks like 32 bits per 3 words, but I thought to share this different contextual view as half of the last word expands entropy artificially). Which leads to the next point I am contemplating: While there are 2048^12 potential 12-word mnemonics, how many of those "possible combinations" are valid mnemonics in terms of checksum? For any 128 random number there is only 1 checksum, but for any random 11 words or 121 bits, there are only 2^7 possible 7-leading bit combinations, each of which maps to a singular checksum in the range (2^4). So the last word always has only 7 bits of entropy for a 12-word mnemonic. Thus the number of potential mnemonics, if I am not mistaken is 2048^11.6363636364. Actually, I just checked and the math works out: 
```2**(log2(2048)*11.6363636364)==2**128```

**Comment by dooglus** [comment]
Each of the first 11 words give 11 bits of entropy. The last word gives 7 more, for a total of 128 bits. The last 4 bits are the checksum. So only 1/16th of 12 word combinations are valid according to the checksum. ie. there are 2^(12*11 - 4) = 2^(132-4) = 2^128 valid 12-word combinations.

The fact that the entropy isn't evenly distributed through the 12 words doesn't matter when deciding how many words to use. The "32 bits per 3 words" is the average over the whole phrase.

**Comment by hatgit** [comment]
Nice to hear your points on this @dooglus, I agree it doesn't matter how we distribute, just as 32 bits per 3 words is still accurate in the overall context of (10.6666666667 bits per word x 3 = 32 bits per 3 words), compared what I said that each word of the first eleven words are 11 bits and only the last is 7, using the 128 bits example. I think the valuable lesson here to others could be 1) in the range of possible 12 word mnemonics (which is 2^132), only 2^128 are valid (as we both agree above), or for any BIP39 randomly chosen 11 words (121 bits), there are only 256 possibly valid checksum words (or 2^7 leading 7-bit combinations, and each of which maps to a checksum in the range 2^4 via the hash function). So that reduction from 2**132 to 2**128, I think can be seen by imagining that instead of choosing from 2048 words for the very last word, the choice is really happening based off 2^7 chances of the last 7 bits in the initial entropy. Of course, overall security is still the same either way, my goal here was to bring some of the nuances to the surface for a healthy talk, thanks!

**Comment by dooglus** [comment]
As you say: if you know the first 11 words, there are only exactly 2^7 = 128 possibilities for the last word that satisfy the checksum. Note also that if you are missing one of the other words instead, ie. you have 11 out of 12 words then there are still only roughly 128 possibilities for the missing word.

For example, if your 12 words are "leaf normal total jump common update rapid chimney soda peasant rural corn". There are 135 different words that work in the 1st position, 117 in the 2nd position, 150 in the 3rd position, ..., and exactly 128 in the 12th position.

**Comment by hatgit** [comment]
Hmm, that's very interesting never thought of it from the start moving left to right (or did you shift all words to the right where the 11th becomes the 12th, and then the first is missing?), why wouldn't each of the first 11 words be possibilities of 1 out 2048 or 2^11? Can you share the calculation? (I'm guessing because of their effect on the final checksum, not sure)

**Comment by dooglus** [comment]
I simply tried replacing the first word with each of the 2048 different words in turn and counted how many of those satisfied the checksum. Since the checksum (the last 4 bits of the 12th word) is just the first 4 bits of the sha256 hash of the entropy (the first 11 words plus the first 7 bits of the 12th word) there's a 1 in 16 chance that it is correct by chance when you change the first word, and so the expected number of valid first words is 2048/16 = 128. The output of the sha256 hash appears random, so the actual number of valid first words usually isn't 128, but is somewhere in that region. Like if you roll a 6 sided die 60 times you would expect to get ten 6's, but wouldn't be surprised if you got 8 or 12 of them too.
