### ISSUE TITLE
Balance of addresses

### ISSUE THREAD

**Issue by DanielWeigl** [dcpos/bip39#6]
Hi, 

i added a balance/tx-lookup for derived addresses to your site - its currently only a quick hack, but would you include it? Then ill brush it up a bit.

You can test it here: https://raw.githack.com/DanielWeigl/bip39/master/src/index.html

(it uses the blockr-api to fetch the data)

**Comment by iancoleman** [comment]
Thanks for the pull request. I like this feature.

Some notes for my own sake when I come back to review this for inclusion
* Balance and txcount value should be separate columns
* Columns should be able to be toggled on/off to make copy/paste of specific values possible
* Total balance can/should be calculated/displayed
* Option to continue generating addresses until the [gap limit](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit) is reached
* Note about the privacy implications of using a third-party api to fetch balances

I'm not 100% sold on this idea, but I can certainly see the appeal. Having a way to view the balance is valuable, but want to spend a bit more time thinking about various ways this may be achieved.

**Comment by iancoleman** [comment]
blockchain.info allows searchy by xpub key to retrieve balances. There is a note about this in the tool now (see https://github.com/dcpos/bip39/commit/aa51da11523b390878d0baa4b66c04e2d6a3c305).

Since there is a privacy issue with this feature, and the tool is intended to be fully featured when used offline, it will not be added. I think searching blockchain.info with xpub keys is adequate.

Thanks for the input all the same.

**Comment by DanielWeigl** [comment]
Thx  np, i understand that the offline aspect of your tool makes it not really applicable to have something like that included.
otoh, we now have a similar tool coded: https://mycelium-com.github.io/masterscan/
